/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algorithm_Simulator;

import java.awt.Color;
import java.awt.Image;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author isuru
 */
public class SelectionSort extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form SelectionSort
     */
    int []arr;
    JLabel []lblArr;
    JLabel []lbl;
    int swapMode;
    Thread th;
    boolean status;
    
    public SelectionSort() {
        initComponents();
        
        try{
        Image i = ImageIO.read(getClass().getResource("/Algorithm_Simulator/icon.png"));
        setIconImage(i);
        }catch(Exception e){
            System.out.println(e);
        }
        lblArr = new JLabel[]{lblNo1,lblNo2,lblNo3,lblNo4,lblNo5,lblNo6,lblNo7,lblNo8,lblNo9,lblNo10};
        lbl = new JLabel[]{lbl1,lbl2,lbl3,lbl4,lbl5,lbl6,lbl7,lbl8,lbl9,lbl10};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNo1 = new javax.swing.JTextField();
        txtNo2 = new javax.swing.JTextField();
        txtNo3 = new javax.swing.JTextField();
        txtNo4 = new javax.swing.JTextField();
        txtNo5 = new javax.swing.JTextField();
        txtNo6 = new javax.swing.JTextField();
        txtNo7 = new javax.swing.JTextField();
        txtNo8 = new javax.swing.JTextField();
        txtNo9 = new javax.swing.JTextField();
        txtNo10 = new javax.swing.JTextField();
        lblNo1 = new javax.swing.JLabel();
        lblNo2 = new javax.swing.JLabel();
        lblNo3 = new javax.swing.JLabel();
        lblNo4 = new javax.swing.JLabel();
        lblNo5 = new javax.swing.JLabel();
        lblNo6 = new javax.swing.JLabel();
        lblNo7 = new javax.swing.JLabel();
        lblNo8 = new javax.swing.JLabel();
        lblNo9 = new javax.swing.JLabel();
        lblNo10 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSort = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algorithm Simulator - Selection Sort");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo1KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 45, 48, 36));

        txtNo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo2KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 45, 48, 36));

        txtNo3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo3KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 45, 48, 36));

        txtNo4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo4KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 45, 48, 36));

        txtNo5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo5KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 45, 48, 36));

        txtNo6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo6KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 45, 48, 36));

        txtNo7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo7KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 45, 48, 36));

        txtNo8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo8KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 45, 48, 36));

        txtNo9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo9KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 45, 48, 36));

        txtNo10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNo10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNo10KeyReleased(evt);
            }
        });
        jPanel1.add(txtNo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 45, 48, 36));

        lblNo1.setBackground(java.awt.Color.lightGray);
        lblNo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo1.setOpaque(true);
        jPanel1.add(lblNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 171, 48, 36));

        lblNo2.setBackground(java.awt.Color.lightGray);
        lblNo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo2.setOpaque(true);
        jPanel1.add(lblNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 171, 48, 36));

        lblNo3.setBackground(java.awt.Color.lightGray);
        lblNo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo3.setOpaque(true);
        jPanel1.add(lblNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 171, 48, 36));

        lblNo4.setBackground(java.awt.Color.lightGray);
        lblNo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo4.setOpaque(true);
        jPanel1.add(lblNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 171, 48, 36));

        lblNo5.setBackground(java.awt.Color.lightGray);
        lblNo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo5.setOpaque(true);
        jPanel1.add(lblNo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 171, 48, 36));

        lblNo6.setBackground(java.awt.Color.lightGray);
        lblNo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo6.setOpaque(true);
        jPanel1.add(lblNo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 171, 48, 36));

        lblNo7.setBackground(java.awt.Color.lightGray);
        lblNo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo7.setOpaque(true);
        jPanel1.add(lblNo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 171, 48, 36));

        lblNo8.setBackground(java.awt.Color.lightGray);
        lblNo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo8.setOpaque(true);
        jPanel1.add(lblNo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 171, 48, 36));

        lblNo9.setBackground(java.awt.Color.lightGray);
        lblNo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo9.setOpaque(true);
        jPanel1.add(lblNo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 171, 48, 36));

        lblNo10.setBackground(java.awt.Color.lightGray);
        lblNo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNo10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblNo10.setOpaque(true);
        jPanel1.add(lblNo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 171, 48, 36));
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 225, 48, 26));
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 225, 48, 26));
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 225, 48, 26));
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 225, 48, 26));
        jPanel1.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 225, 48, 26));
        jPanel1.add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 225, 48, 26));
        jPanel1.add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 225, 48, 26));
        jPanel1.add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 225, 48, 26));
        jPanel1.add(lbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 225, 48, 26));
        jPanel1.add(lbl10, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 225, 48, 26));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Input");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Output");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 109, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\isuru\\Documents\\NetBeansProjects\\algorithmsimulator\\src\\Algorithm_Simulator\\2.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 280));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setText("7            exchange A [ j ] <---> A [ small ]");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, -1, -1));

        jLabel15.setText("6               then small <--- i");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        jLabel14.setText("5               do if A [ i ] < A [ small ]");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, -1, -1));

        jLabel13.setText("4            for i <--- j + 1 to n");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        jLabel12.setText("3         do small <--- j");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel11.setText("2      for j <--- 1 to n - 1");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        jLabel10.setText("1   n <--- length [ A ]");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Algorithm");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 11, 86, 26));

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        jPanel2.add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 240, 37));

        btnRandom.setText("Random");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });
        jPanel2.add(btnRandom, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 240, 37));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 240, 37));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 240, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\isuru\\Documents\\NetBeansProjects\\algorithmsimulator\\src\\Algorithm_Simulator\\1.jpg")); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        
        Random ran = new Random();
        
        txtNo1.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo2.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo3.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo4.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo5.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo6.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo7.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo8.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo9.setText(String.valueOf(ran.nextInt(101) + 0));
        txtNo10.setText(String.valueOf(ran.nextInt(101) + 0));
        
        setValues();
    }//GEN-LAST:event_btnRandomActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        
        th = new Thread(this);
        status = getValues();
        
        if(status == true){
          //  lbl = new JLabel[]{lbl1,lbl2,lbl3,lbl4,lbl5,lbl6,lbl7,lbl8,lbl9,lbl10};
            swapMode = 1;
            th.start();
        }
    }//GEN-LAST:event_btnSortActionPerformed

    private void txtNo1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo1KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo1KeyReleased

    private void txtNo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo2KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo2KeyReleased

    private void txtNo3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo3KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo3KeyReleased

    private void txtNo4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo4KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo4KeyReleased

    private void txtNo5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo5KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo5KeyReleased

    private void txtNo6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo6KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo6KeyReleased

    private void txtNo7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo7KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo7KeyReleased

    private void txtNo8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo8KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo8KeyReleased

    private void txtNo9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo9KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo9KeyReleased

    private void txtNo10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNo10KeyReleased
        setValues();
    }//GEN-LAST:event_txtNo10KeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionSort().setVisible(true);
            }
        });
    }
    
    public void setValues() {        
        lblNo1.setText(txtNo1.getText());
        lblNo2.setText(txtNo2.getText());
        lblNo3.setText(txtNo3.getText());
        lblNo4.setText(txtNo4.getText());
        lblNo5.setText(txtNo5.getText());
        lblNo6.setText(txtNo6.getText());
        lblNo7.setText(txtNo7.getText());
        lblNo8.setText(txtNo8.getText());
        lblNo9.setText(txtNo9.getText());
        lblNo10.setText(txtNo10.getText());
    }
    
    public boolean getValues() {
        arr = new int[10];
        
        

        if (txtNo1.getText().isEmpty() || txtNo2.getText().isEmpty() || txtNo3.getText().isEmpty() || txtNo4.getText().isEmpty() || txtNo5.getText().isEmpty() || txtNo6.getText().isEmpty() || txtNo7.getText().isEmpty() || txtNo8.getText().isEmpty() || txtNo9.getText().isEmpty() || txtNo10.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all the required fields...!");
            return false;
        } else {
            try {
                arr[0] = Integer.parseInt(txtNo1.getText());
                arr[1] = Integer.parseInt(txtNo2.getText());
                arr[2] = Integer.parseInt(txtNo3.getText());
                arr[3] = Integer.parseInt(txtNo4.getText());
                arr[4] = Integer.parseInt(txtNo5.getText());
                arr[5] = Integer.parseInt(txtNo6.getText());
                arr[6] = Integer.parseInt(txtNo7.getText());
                arr[7] = Integer.parseInt(txtNo8.getText());
                arr[8] = Integer.parseInt(txtNo9.getText());
                arr[9] = Integer.parseInt(txtNo10.getText());

                return true;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please enter valid numbers...!");
                return false;
            }
        }
    }
    
    public void selectionSort() throws InterruptedException{
        int temp, smallest;
        
        if(swapMode == 1){
            for(int i=0; i<arr.length-1; i++){
                smallest = i;
                
                for(int j=i+1; j<arr.length; j++){
                    //test
                    lblArr[smallest].setBackground(Color.PINK);
                //    lbl[smallest].setText("smallest");
                    lblArr[j].setBackground(Color.YELLOW);
                    th.sleep(1000);
                    lblArr[smallest].setBackground(Color.LIGHT_GRAY);
                //    lbl[smallest].setText("");
                    lblArr[j].setBackground(Color.LIGHT_GRAY);
                    //test
                    if(arr[j] < arr[smallest]){
                        smallest = j;                        
                    }
                }
                temp = arr[smallest];
                arr[smallest] = arr[i];
                arr[i] = temp;
                lblArr[smallest].setBackground(Color.WHITE);
                if(i == arr.length-2){
                    lblArr[9].setBackground(Color.WHITE);
                }
                
                try{
                    swap(i,smallest);
                }catch(InterruptedException e){}
            }
        }
        JOptionPane.showMessageDialog(null, "Successfully Sorted");
    }
    
    public void swap(int num1, int num2) throws InterruptedException{
        for(int i=0; i<15; i++){
            lblArr[num1].setLocation(lblArr[num1].getLocation().x, lblArr[num1].getLocation().y+3);
            lblArr[num2].setLocation(lblArr[num2].getLocation().x, lblArr[num2].getLocation().y-3);
            th.sleep(15);
        }
        int length = lblArr[num2].getLocation().x - lblArr[num1].getLocation().x;
        for(int i=0; i<length; i++){
            lblArr[num1].setLocation(lblArr[num1].getLocation().x+1, lblArr[num1].getLocation().y);
            lblArr[num2].setLocation(lblArr[num2].getLocation().x-1, lblArr[num2].getLocation().y);
            th.sleep(15);
        }
        for(int i=0; i<15; i++){
            lblArr[num1].setLocation(lblArr[num1].getLocation().x, lblArr[num1].getLocation().y-3);
            lblArr[num2].setLocation(lblArr[num2].getLocation().x, lblArr[num2].getLocation().y+3);
            th.sleep(15);
        }
        JLabel temp = lblArr[num1];
        lblArr[num1] = lblArr[num2];
        lblArr[num2] = temp;
    }
    
    public void clearFields() {
        txtNo1.setText("");
        txtNo2.setText("");
        txtNo3.setText("");
        txtNo4.setText("");
        txtNo5.setText("");
        txtNo6.setText("");
        txtNo7.setText("");
        txtNo8.setText("");
        txtNo9.setText("");
        txtNo10.setText("");

        lblNo1.setText("");
        lblNo2.setText("");
        lblNo3.setText("");
        lblNo4.setText("");
        lblNo5.setText("");
        lblNo6.setText("");
        lblNo7.setText("");
        lblNo8.setText("");
        lblNo9.setText("");
        lblNo10.setText("");
        
        for(int a=0; a<10; a++){
            lblArr[a].setBackground(Color.LIGHT_GRAY);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnSort;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    private javax.swing.JLabel lblNo1;
    private javax.swing.JLabel lblNo10;
    private javax.swing.JLabel lblNo2;
    private javax.swing.JLabel lblNo3;
    private javax.swing.JLabel lblNo4;
    private javax.swing.JLabel lblNo5;
    private javax.swing.JLabel lblNo6;
    private javax.swing.JLabel lblNo7;
    private javax.swing.JLabel lblNo8;
    private javax.swing.JLabel lblNo9;
    private javax.swing.JTextField txtNo1;
    private javax.swing.JTextField txtNo10;
    private javax.swing.JTextField txtNo2;
    private javax.swing.JTextField txtNo3;
    private javax.swing.JTextField txtNo4;
    private javax.swing.JTextField txtNo5;
    private javax.swing.JTextField txtNo6;
    private javax.swing.JTextField txtNo7;
    private javax.swing.JTextField txtNo8;
    private javax.swing.JTextField txtNo9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            selectionSort();
        } catch (InterruptedException ex) {
            Logger.getLogger(SelectionSort.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
